#!/bin/bash
# Manual control demo for SwarmNav-Sim robots

echo "========================================="
echo "SwarmNav-Sim Manual Control Demo"
echo "========================================="
echo ""
echo "Current Status:"
echo "  ✅ Ignition Gazebo running"
echo "  ✅ 3 robots spawned in warehouse"
echo "  ✅ Robot models visible"
echo "  ⚠️  Sensors not working (need SDF format)"
echo ""
echo "You can manually control the robots using keyboard:"
echo ""
echo "To control robot_0:"
echo "  ros2 run teleop_twist_keyboard teleop_twist_keyboard \\"
echo "    --ros-args --remap cmd_vel:=/robot_0/cmd_vel"
echo ""
echo "To control robot_1:"
echo "  ros2 run teleop_twist_keyboard teleop_twist_keyboard \\"
echo "    --ros-args --remap cmd_vel:=/robot_1/cmd_vel"
echo ""
echo "To control robot_2:"
echo "  ros2 run teleop_twist_keyboard teleop_twist_keyboard \\"
echo "    --ros-args --remap cmd_vel:=/robot_2/cmd_vel"
echo ""
echo "Controls:"
echo "  i - forward"
echo "  k - stop"
echo "  j - turn left"
echo "  l - turn right"
echo "  u - forward + left"
echo "  o - forward + right"
echo "  m - backward"
echo "  , - backward + left"
echo "  . - backward + right"
echo ""
echo "Note: The robots won't move because the differential drive"
echo "      plugin isn't loaded. This is because we're using URDF"
echo "      instead of SDF format for Ignition Gazebo."
echo ""
echo "To fix this, we need to:"
echo "  1. Convert robot model to SDF format, OR"
echo "  2. Switch to Gazebo Classic (gazebo11)"
echo ""
echo "========================================="
